hydra:
  run:
    dir: ./results/${now:%Y-%m-%d}/${now:%H-%M-%S}
#    dir: /project/results/${now:%Y-%m-%d}/${now:%H-%M-%S}

data:
  name: tinyimagenet
  root: /project/data/tiny-imagenet-200
  train: train
  val: val
  test: test
  train_labels: words.txt
  val_labels: val_annotations.txt
  classes: 200

results:
  checkpoints:
    root: checkpoints
    tag: model
    name: model

train:
  epochs: 2
  batch_size: 256
  num_workers: 2

model:
  name: resnet18
  pretrained: False
