hydra:
  run:
    dir: results/${model.arch}/${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - data: tinyimagenet

augmentation:
  root: config/augmentation/default.yaml

results:
  checkpoints:
    root: checkpoints
    tag: tensorboard
    name: model

train:
  epochs: 2
  batch_size: 256
  num_workers: 2
  monitor: val_acc

model:
  arch: resnet18
  pretrained: false

optimizer:
  name: SGD
  parameters:  # passed as **kwargs
    lr: 0.1
    momentum: 0.9
    weight_decay: 1e-8

scheduler:
  name: CosineAnnealingLR
  parameters:  # passed as **kwargs
    T_max: 1955  # default train loader has 391 steps